export const gradePatientCase = async (patientData) => {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('VITE_GEMINI_API_KEY is not set in the .env file.');
  }

  const prompt = `You are an expert AI radiologist assisting in grading lumbar spine degenerative classification.
Given the following patient metadata (series descriptions and annotated condition coordinates from MRI slices), 
predict the severity grades for the 25 conditions.

Patient ID: ${patientData.study_id}
Total Coordinates Available: ${patientData.coordinates.length}
Series Available: ${patientData.series.map(s => s.description).join(', ')}

Coordinate Data Snippet:
${JSON.stringify(patientData.coordinates.map(c => ({
  condition: c.condition,
  level: c.level,
  x: c.x,
  y: c.y
})), null, 2)}

Conditions to grade:
spinal_canal_stenosis, left_neural_foraminal_narrowing, right_neural_foraminal_narrowing, left_subarticular_stenosis, right_subarticular_stenosis
Across 5 levels: l1_l2, l2_l3, l3_l4, l4_l5, l5_s1

Valid output grades MUST BE strictly one of: "Normal/Mild", "Moderate", or "Severe".

Provide your response in purely valid JSON format following this exact schema:
{
  "explanation": "A short 1-2 sentence medical explanation based strictly on the coordinate density and series descriptions.",
  "grades": {
    "spinal_canal_stenosis_l1_l2": "Normal/Mild",
    "spinal_canal_stenosis_l2_l3": "Normal/Mild",
    "spinal_canal_stenosis_l3_l4": "Normal/Mild",
    "spinal_canal_stenosis_l4_l5": "Normal/Mild",
    "spinal_canal_stenosis_l5_s1": "Normal/Mild",
    "left_neural_foraminal_narrowing_l1_l2": "Normal/Mild",
    "left_neural_foraminal_narrowing_l2_l3": "Normal/Mild",
    "left_neural_foraminal_narrowing_l3_l4": "Normal/Mild",
    "left_neural_foraminal_narrowing_l4_l5": "Normal/Mild",
    "left_neural_foraminal_narrowing_l5_s1": "Normal/Mild",
    "right_neural_foraminal_narrowing_l1_l2": "Normal/Mild",
    "right_neural_foraminal_narrowing_l2_l3": "Normal/Mild",
    "right_neural_foraminal_narrowing_l3_l4": "Normal/Mild",
    "right_neural_foraminal_narrowing_l4_l5": "Normal/Mild",
    "right_neural_foraminal_narrowing_l5_s1": "Normal/Mild",
    "left_subarticular_stenosis_l1_l2": "Normal/Mild",
    "left_subarticular_stenosis_l2_l3": "Normal/Mild",
    "left_subarticular_stenosis_l3_l4": "Normal/Mild",
    "left_subarticular_stenosis_l4_l5": "Normal/Mild",
    "left_subarticular_stenosis_l5_s1": "Normal/Mild",
    "right_subarticular_stenosis_l1_l2": "Normal/Mild",
    "right_subarticular_stenosis_l2_l3": "Normal/Mild",
    "right_subarticular_stenosis_l3_l4": "Normal/Mild",
    "right_subarticular_stenosis_l4_l5": "Normal/Mild",
    "right_subarticular_stenosis_l5_s1": "Normal/Mild"
  }
}

Do not include markdown wrappers (like \`\`\`json) or any other text. Output strictly valid JSON.`;

  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }]
        }],
        generationConfig: {
          responseMimeType: "application/json"
        }
      })
    });
    
    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Status ${response.status}: ${errorText}`);
    }
    
    const data = await response.json();
    let aiText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!aiText) {
        throw new Error("No text generated by Gemini.");
    }
    
    if (aiText.includes('```json')) {
      aiText = aiText.split('```json')[1].split('```')[0].trim();
    } else if (aiText.includes('```')) {
      aiText = aiText.split('```')[1].split('```')[0].trim();
    }
    
    return JSON.parse(aiText);
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw new Error("Failed to grade patient case: " + error.message);
  }
};
